### ISSUE TITLE
Optimistic concurrency control through sequence number

### ISSUE THREAD

**Issue by AbstractiveNord** [fjall-rs/fjall#39]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to ensure you work with latest key version.

**Describe the solution you'd like**
Make possible to keys have sequence number, which may be used for denying modifying operations, if last sequence of stream and requested number doesn't match.

**Comment by marvin-j97** [comment]
> Currently it's not possible to ensure you work with latest key version.
This is true, reads & writes are not happening under some transactional context. My goal is to have an opt-in way to get transaction support, [like in RocksDB](https://github.com/facebook/rocksdb/wiki/Transactions). See https://github.com/fjall-rs/fjall/issues/30.

> Make possible to keys have sequence number
All key-value pairs already have a sequence number associated with them, that's how snapshot support works (https://docs.rs/fjall/latest/fjall/struct.PartitionHandle.html#method.snapshot).

**Comment by marvin-j97** [comment]
Optimistic concurrency control (w/ serializable snapshot isolation) will be implemented by https://github.com/fjall-rs/fjall/pull/79

**Comment by marvin-j97** [comment]
Implemented in https://github.com/fjall-rs/fjall/pull/79
