### ISSUE TITLE
Recreating a deleted partition may be undefined behaviour

### ISSUE THREAD

**Issue by marvin-j97** [fjall-rs/fjall#59]
Reproduce:
1. Delete a partition
2. A partition may not be cleaned up until all handles to it are dropped, the partition folder is marked with a `.deleted` marker
3. At this point, the keyspace forgot about the partition, now recreate the partition
4. No idea what happens: Need to check if the partition folder exists AND `.deleted` marker exists
5. When the handles of the "old" partition are dropped, the partition folder will be deleted, even after we "recreated" it, see step 4 for solution

**Comment by dharanad** [comment]
Hello @marvin-j97 
I am new here and would like to pick up this issue

**Comment by marvin-j97** [comment]
> Hello @marvin-j97 I am new here and would like to pick up this issue

Hi, sure. My idea was to check for the `.deleted` marker in the partition folder when creating a partition, and then throwing an error (Error::PartitionDeleted), if it exists. That should also be easy to test by keeping a partition handle around, "delete" the partition, then recreating it.
