### ISSUE TITLE
Feature request: memory backend

### ISSUE THREAD

**Issue by beckend** [fjall-rs/fjall#66]
For testing purposes, cleaning up is a hassle.

**Comment by marvin-j97** [comment]
I think the extra complexity doesn't really warrant implementing this. Instead, a "temporary" configuration could be used maybe. Fjall already uses tempfile internally, so that could be reused to create a temporary folder and clean it up automatically?

**Comment by beckend** [comment]
With that config, you could always change the internals freely. There point is database is going to be used in tests after all if it ever strives to production.

**Comment by beckend** [comment]
I did what you suggest, how about that?
