### ISSUE TITLE
Reproduceable benchmarks?

### ISSUE THREAD

**Issue by arthurprs** [fjall-rs/fjall#81]
Benchmarks [posted in the blog](https://fjall-rs.github.io/post/announcing-fjall-2/) look cool. I guess they are from https://github.com/marvin-j97/rust-storage-bench? If so, it seems like the repo isn't up to date. It'd be best long-term if they were reproducible.

**Comment by arthurprs** [comment]
I suggest you add a public domain [Shakespeare works](https://www.gutenberg.org/cache/epub/100/pg100.txt) (5.6mb) and pick the desired range out of it (wrapping around as needed).

I also got a few changes I'd like to send over (including the above), but I wasn't sure if it made sense given that it was seemingly outdated.

**Comment by marvin-j97** [comment]
> I also got a few changes I'd like to send over (including the above), but I wasn't sure if it made sense given that it was seemingly outdated.

I think it does. If I get around to finishing a rewrite I could incorporate them. That being said, the benchmark repo isn't necessarily outdated (I just need to bump fjall to 2.0), it just has way less and different workloads than I am using now locally.

**Comment by arthurprs** [comment]
I opened a PR [here](https://github.com/marvin-j97/rust-storage-bench/pull/6)

**Comment by marvin-j97** [comment]
The bench repo's v1 will have standalone HTML exports, and copyable scripts to reproduce each benchmark report.

I'll see that in the future benchmarks will a accompanying HTML report.
