### ISSUE TITLE
Add some info where does the name of the project come from and how to pronounce it correctly

### ISSUE THREAD

**Issue by qrilka** [fjall-rs/fjall#83]
**Describe the solution you'd like**
Text (in README?) answers the questions from the title of this request

**Comment by marvin-j97** [comment]
Fjall is just "Mountain" in a [multitude of Nordic languages](https://en.wiktionary.org/wiki/fjall), so pronounciation depends, I tend to go with /fjɑlː/.
I may add something to the README when I get around to redesigning it a little.
